version: "3"
services:
  flaskapp:
    build: app
    ports:
     - "5000:5000"
    environment:
     - AWS_PROFILE=csloginteacher
     - AWS_PROFILE=csloginstudent
    volumes:
     - cred:/home/.aws/credentials
volumes:
  cred:
